GET http://localhost:3000/subscribers

### 

GET http://localhost:3000/subscribers/63764031ab93944a436bf57c

### 

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Jesus",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/637642972920f05735cde28c

### 

PATCH http://localhost:3000/subscribers/63764031ab93944a436bf57c
Content-Type: application/json

{
    "subscribedToChannel": "WDS"
}